import type { CallRecord } from './types';

export const CALLS: CallRecord[] = [
  {
    id: 'CCR-4821',
    reference: 'CCR-4821',
    priority: 'critical',
    customer: 'Maya Patel',
    agent: 'Daniel Brooks',
    date: '25 Aug 2026',
    time: '09:14',
    startedAt: '2026-08-25T09:14:00.000Z',
    duration: '7m 42s',
    durationSeconds: 462,
    intent: 'Suspected card fraud',
    mood: 'angry',
    resolution: 'unresolved',
    score: 96,
    needsAttention: true,
    initialMood: 'neutral',
    moodShiftAtSeconds: 277,
    moodTimeline: [],
    evidence: [],
  },
  {
    id: 'CCR-4803',
    reference: 'CCR-4803',
    priority: 'high',
    customer: 'Oliver Smith',
    agent: 'Priya Shah',
    date: '25 Aug 2026',
    time: '10:02',
    startedAt: '2026-08-25T10:02:00.000Z',
    duration: '5m 18s',
    durationSeconds: 318,
    intent: 'Refund not received',
    mood: 'frustrated',
    resolution: 'partially_resolved',
    score: 82,
    needsAttention: true,
    initialMood: 'neutral',
    moodShiftAtSeconds: null,
    moodTimeline: [],
    evidence: [],
  },
  {
    id: 'CCR-4795',
    reference: 'CCR-4795',
    priority: 'high',
    customer: 'Sophia Williams',
    agent: 'James Wilson',
    date: '24 Aug 2026',
    time: '16:37',
    startedAt: '2026-08-24T16:37:00.000Z',
    duration: '6m 05s',
    durationSeconds: 365,
    intent: 'Duplicate card charge',
    mood: 'frustrated',
    resolution: 'unresolved',
    score: 78,
    needsAttention: true,
    initialMood: 'neutral',
    moodShiftAtSeconds: null,
    moodTimeline: [],
    evidence: [],
  },
  {
    id: 'CCR-4784',
    reference: 'CCR-4784',
    priority: 'medium',
    customer: 'Noah Brown',
    agent: 'Amara Khan',
    date: '24 Aug 2026',
    time: '14:20',
    startedAt: '2026-08-24T14:20:00.000Z',
    duration: '4m 11s',
    durationSeconds: 251,
    intent: 'Online banking locked',
    mood: 'neutral',
    resolution: 'resolved',
    score: 54,
    needsAttention: true,
    initialMood: 'neutral',
    moodShiftAtSeconds: null,
    moodTimeline: [],
    evidence: [],
  },
  {
    id: 'CCR-4771',
    reference: 'CCR-4771',
    priority: 'low',
    customer: 'Emma Taylor',
    agent: 'Liam Jones',
    date: '23 Aug 2026',
    time: '11:55',
    startedAt: '2026-08-23T11:55:00.000Z',
    duration: '3m 30s',
    durationSeconds: 210,
    intent: 'Address change',
    mood: 'positive',
    resolution: 'resolved',
    score: 18,
    needsAttention: false,
    initialMood: 'neutral',
    moodShiftAtSeconds: null,
    moodTimeline: [],
    evidence: [],
  },
];

export const CALL_SUMMARIES: Record<string, string> = {
  'CCR-4821':
    'Maya reported three card transactions she did not recognise. Her frustration increased after learning the card could not be immediately replaced. The card was blocked, but the disputed transactions remain unresolved.',
  'CCR-4803':
    'Oliver requested a status update on a refund from a disputed payment made three weeks ago. Agent confirmed receipt but could not provide an exact timeline. Case escalated to the billing team.',
  'CCR-4795':
    'Sophia identified two identical charges on her statement dated 22 Aug. Agent initiated a dispute claim but could not reverse the charge immediately. Customer expressed dissatisfaction with the timeline.',
  'CCR-4784':
    'Noah was locked out of online banking after multiple failed login attempts. Agent reset access via authenticated verification. Account access was fully restored during the call.',
  'CCR-4771':
    'Emma requested an update to her home address following a recent move. Agent completed the address change after identity verification. Emma confirmed the update was correct.',
};

export const TRANSCRIPT_TURNS = [
  { speaker: 'Agent', time: '00:05', text: "Thank you for calling First National Bank. This is Daniel, how can I help you today?", highlight: false },
  { speaker: 'Customer', time: '00:11', text: "Hi, yes — my name is Maya Patel. I need to report some transactions on my account that I don't recognise.", highlight: false },
  { speaker: 'Agent', time: '00:20', text: "I'm sorry to hear that, Maya. Let me pull up your account. Can you confirm your date of birth and the last four digits of your card?", highlight: false },
  { speaker: 'Customer', time: '00:30', text: "It's the fourteenth of March 1988, and the last four digits are 7742.", highlight: false },
  { speaker: 'Agent', time: '00:42', text: "Thank you. I can see your account now. Can you tell me which transactions you're concerned about?", highlight: false },
  { speaker: 'Customer', time: '00:49', text: "There are three charges I don't recognise. All from yesterday — one for £89.99, one for £124.50, and one for £67.00. I've never heard of these merchants.", highlight: false },
  { speaker: 'Agent', time: '01:05', text: "I can see those transactions. Let me flag them for investigation. Have you contacted us about this before?", highlight: false },
  { speaker: 'Customer', time: '01:12', text: "I've already reported this twice and the transactions are still showing.", highlight: true },
  { speaker: 'Agent', time: '02:14', text: "I apologise for the repeated contact, Maya. I can see two previous reports on the account. I'll escalate this as a priority case right away.", highlight: false },
  { speaker: 'Customer', time: '02:28', text: "What does that actually mean? When will the money be back in my account?", highlight: false },
  { speaker: 'Agent', time: '02:35', text: "Our disputes team will review the transactions. It can take up to ten working days once the investigation begins.", highlight: false },
  { speaker: 'Customer', time: '04:37', text: "So you can't tell me when I'll get my money back?", highlight: true },
  { speaker: 'Agent', time: '05:02', text: "The investigation may take up to fifteen working days.", highlight: true },
  { speaker: 'Customer', time: '05:10', text: "That's almost a month. This is completely unacceptable. I need my money back.", highlight: false },
  { speaker: 'Agent', time: '05:20', text: "I completely understand your frustration. I'll block the card immediately to prevent further transactions and flag this for our senior disputes team.", highlight: false },
  { speaker: 'Customer', time: '05:35', text: "Fine. But I want confirmation of everything done today sent to my email.", highlight: false },
  { speaker: 'Agent', time: '05:41', text: "Absolutely. I'll send a confirmation email within the hour. The card is now blocked and the case has been escalated.", highlight: false },
];
